## Project
name: nefinance_intelligence
version: "1.0"
config-version: 2
profile: nefinance_intelligence

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_packages]

## Models
models:
  nefinance_intelligence:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    core:
      +materialized: table
    mart:
      +materialized: table
