nefinance_intelligence:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ""
      user: ""
      role: ACCOUNTADMIN
      database: NEFINANCE_DB
      schema: DEV
      warehouse: COMPUTE_WH
      threads: 8
    prod:
      type: snowflake
      account: ""
      user: ""
      role: ACCOUNTADMIN
      database: NEFINANCE_DB
      schema: PROD
      warehouse: COMPUTE_WH
      threads: 8
